name: CI Pipeline

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests (demonstracja)
        run: |
          echo "Test - w tym miejscu mogłyby zostać uruchomione testy jednostkowe"

      - name: Log in to GitHub Container Registry
        if: github.event_name == 'push'  # lub warunek, który wolisz
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t my-flask-app:${{ github.sha }} .

      - name: Push Docker image
        if: github.event_name == 'push'
        run: |
          docker tag my-flask-app:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/my-flask-app:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/my-flask-app:${{ github.sha }}
